### ISSUE TITLE
Cannot proxy DTE.Property object as let_value does not get proxied.

### ISSUE THREAD

**Issue by timbrown5** [mtamme/NProxy#7]
The exception i get is:

> Message: System.TypeLoadException : Method 'let_Value' in type 'NProxy.Dynamic.<Proxy>z__0' from assembly 'NProxy.Dynamic, Version=2.3.0.0, Culture=neutral, PublicKeyToken=d1533b3017fed9c3' does not have an implementation.

This seems to be due to let_Value being a special name, so the VisitMethods doesn't visit it (ProxyDefinitionVisitorExtensions line: 143), but also not being visited as part of the Property generation (as this is normally get/set, no let).

The Docs for this class are here:
https://docs.microsoft.com/en-us/dotnet/api/envdte.property.let_value?view=visualstudiosdk-2017

The interface is a little unique, but as this is a third party (Microsoft) interface we have no way of modifying it our end.

**Comment by timbrown5** [comment]
The stacktrace is here:

Result StackTrace:	
at System.Reflection.Emit.TypeBuilder.TermCreateClass(RuntimeModule module, Int32 tk, ObjectHandleOnStack type)
   at System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
   at System.Reflection.Emit.TypeBuilder.CreateType()
   at NProxy.Core.ProxyTypeBuilder.CreateType() in C:\Users\gbbrownt\Downloads\NProxy-e3d6be9a415e12c9470ee710690947c51a2045d9\Source\Main\NProxy.Core\ProxyTypeBuilder.cs:line 419
   at NProxy.Core.ProxyGenerator.GenerateProxyTemplate(IProxyDefinition proxyDefinition) in C:\Users\gbbrownt\Downloads\NProxy-e3d6be9a415e12c9470ee710690947c51a2045d9\Source\Main\NProxy.Core\ProxyGenerator.cs:line 90
   at NProxy.Core.ProxyFactory.GenerateProxyTemplate(IProxyDefinition proxyDefinition) in C:\Users\gbbrownt\Downloads\NProxy-e3d6be9a415e12c9470ee710690947c51a2045d9\Source\Main\NProxy.Core\ProxyFactory.cs:line 109
   at NProxy.Core.Internal.Caching.LockOnWriteCache`2.GetOrAdd(TKey key, Func`2 valueFactory) in C:\Users\gbbrownt\Downloads\NProxy-e3d6be9a415e12c9470ee710690947c51a2045d9\Source\Main\NProxy.Core\Internal\Caching\LockOnWriteCache.cs:line 96
   at NProxy.Core.ProxyFactory.GetProxyTemplate(Type declaringType, IEnumerable`1 interfaceTypes) in C:\Users\gbbrownt\Downloads\NProxy-e3d6be9a415e12c9470ee710690947c51a2045d9\Source\Main\NProxy.Core\ProxyFactory.cs:line 127

**Comment by mtamme** [comment]
Hi @timbrown5, I've commited a fix for this issue. Can you give it a try?

**Comment by timbrown5** [comment]
It appears to work, however I have had to make another change in order to allow creating a proxy of a COM Object (which I failed to mention before).

Annoyingly if you call GetType on a COMObject it will always return System::__ComObject (instead of the actual object the com object represents). https://stackoverflow.com/questions/1429548/how-to-get-type-of-com-object
Inorder to work around this I also have to change MethodInfoBase.cs (Line 210) from this:
```
if (!_declaringType.IsAssignableFrom(targetType))
    throw new TargetException(Resources.MethodNotDeclaredOrInherited);
```

To this:
```
if (!targetType.IsCOMObject)
{
    if (!_declaringType.IsAssignableFrom(targetType))
        throw new TargetException(Resources.MethodNotDeclaredOrInherited);
}
```
This means that the code will blindly call the method when used on a on a COM Object, which may not be desirable behavior in your case.

That said when I add the above change to the the fix you provided in trunk it fixes this issue (I no longer get let_Value not implemented) and I can proxy DTE.

**Comment by mtamme** [comment]
I think the explicit check for COM objects is okay when you do it as follows:
`
if (!_declaringType.IsAssignableFrom(targetType) && !targetType.IsCOMObject)
                throw new TargetException(Resources.MethodNotDeclaredOrInherited);
`
This would not impact the performance for non-COM object invocations.

**Comment by mtamme** [comment]
I've commited the change.

**Comment by timbrown5** [comment]
I will have a look at this tomorrow (I started refactoring a little bit and need to finish before I can test).

Cheers,
Tim

**Comment by timbrown5** [comment]
This is now working for me.

I have tried:
https://msdn.microsoft.com/en-us/library/system.runtime.remoting.proxies.realproxy(v=vs.110).aspx
http://www.castleproject.org/projects/dynamicproxy/
https://www.codeproject.com/Articles/100710/Using-DynamicObject-to-Implement-General-Proxy-Cla
https://www.codeproject.com/Articles/5511/Dynamic-Proxy-Creation-Using-C-Emit
https://www.codeproject.com/Articles/18676/Dynamic-Code-Generation-using-CodeDOM
http://geekswithblogs.net/abhijeetp/archive/2010/04/04/a-simple-dynamic-proxy.aspx
https://github.com/Curit/DynamicProxy

I wasn't able to get any of these to do what I wanted (proxying the DTE interface). This is the only one that enables me to proxy COM interfaces and non-COM interfaces (IEnumerable) with the same solution.

Thanks a lot for your help,
Tim
